[package]
name = "binary"
version = "0.1.0"
edition = "2021"

[dependencies]
rustpython-vm = "0.3.0"
rustpython = "0.3.0"

[profile.release]
lto = true
strip = true
panic = "abort"
opt-level = "s"
codegen-units = 1
